openssh:
  replicas: 1
  restartPolicy: Always

  # Evaluated by the post-install hook
  sleepyTime: "10"

  # TODO: upload openssh-image to docker hub or local registry
  # image: openssh:latest
  imagePullPolicy: IfNotPresent

  service:
    annotations: {}
    clusterIP: ""
    externalIPs: []
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
    type: ClusterIP
    port: 8888
    nodePort: ""

  podAnnotations: {}

  resources: {}

  nodeSelector: {}

usersAuthorizedKeysFsConsumer:
  image: users-authorized-keys-fs-consumer:latest
  imagePullPolicy: IfNotPresent
  replicas: 1
  restartPolicy: Always

worker:
  image: worker:latest
  imagePullPolicy: IfNotPresent

  users:
    replicas: 1
    restartPolicy: Always

api:
  users:
    replicas: 1
    restartPolicy: Always
